Models/LeapYear.cs
using System.ComponentModel.DataAnnotations;

namespace LeapYearDatabase.Models
{
    public class LeapYear
    {
        public int Id { get; set; }

        public DateTime Date { get; set; }

        [Display(Name = "Rok urodzenia")]
        [Range(1899, 2022, ErrorMessage = "Oczekiwana wartość {0} z zakresu {1} i {2}.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "{0} może zawierać jedynie liczby całkowite")]
        [Required(ErrorMessage = "Pole jest obowiązkowe")]
        public int? Year { get; set; }

        [Display(Name = "Imię")]
        [StringLength(maximumLength: 100, ErrorMessage = "{0} nie może przekraczać {1} znaków")]
        [RegularExpression("^[a-zA-ZąĄćĆęĘłŁńŃóÓśŚżŻźŹ]+$", ErrorMessage = "{0} może zawierać jedynie litery")]
        [Required(ErrorMessage = "Pole jest obowiązkowe")]
        public string? Name { get; set; }

        [Display(Name = "Nazwisko")]
        [StringLength(maximumLength: 100, ErrorMessage = "{0} nie może przekraczać {1} znaków")]
        [RegularExpression("^[a-zA-ZąĄćĆęĘłŁńŃóÓśŚżŻźŹ]+$", ErrorMessage = "{0} może zawierać jedynie litery")]
        [Required(ErrorMessage = "Pole jest obowiązkowe")]
        public string Surname { get; set; }

        public string IsLeapYear(int? year)
        {
            if ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0)
            {
                return "";
            }

            return "nie";
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LeapYearDatabase.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LeapYearDatabase.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using LeapYearDatabase.Data;
using Microsoft.EntityFrameworkCore;

namespace LeapYearDatabase.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly LeapYearContext _context;

        [BindProperty]
        public LeapYear LeapYear { get; set; }

        public string[] Arr;
        public IList<LeapYear> LeapYears { get; set; }

        public IndexModel(ILogger<IndexModel> logger, LeapYearContext context)
        {
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                LeapYear.Date = DateTime.Now;

                Arr = new string[4];
                Arr[0] = LeapYear.Name;
                Arr[1] = LeapYear.Surname;
                Arr[2] = LeapYear.Year.ToString();
                Arr[3] = LeapYear.IsLeapYear(LeapYear.Year);


                List<string[]> List;

                var Data = HttpContext.Session.GetString("CheckedList");
                if (Data != null)
                    List = JsonConvert.DeserializeObject<List<string[]>>(Data);
                else
                    List = new List<string[]>();

                List.Add(Arr);
                HttpContext.Session.SetString("CheckedList", JsonConvert.SerializeObject(List));

                LeapYears = _context.LeapYear.ToList();
                _context.LeapYear.Add(LeapYear);
                _context.SaveChanges();

            }
            return Page();
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LeapYearDatabase.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/RecentlySearched.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LeapYearDatabase.Data;
using LeapYearDatabase.Models;

namespace LeapYearDatabase.Pages
{
    public class RecentlySearchedModel : PageModel
    {
        private readonly LeapYearContext _context;

        public IList<LeapYear> LeapYears { get; set; }

        public RecentlySearchedModel(LeapYearContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            LeapYears = _context.LeapYear.OrderByDescending(l => l.Date).Take(20).ToList();
        }

        public IActionResult OnPostDeleteRecord(int RecordId)
        {
            _context.Remove(_context.LeapYear.Single(l => l.Id == RecordId));
            _context.SaveChanges();
            return RedirectToPage("./RecentlySearched");
        }
    }
}

Pages/SavedInSession.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using LeapYearDatabase.Models;

namespace LeapYearDatabase.Pages
{
    public class SavedInSessionModel : PageModel
    {
        public List<string[]> List;

        public void OnGet()
        {
            var Data = HttpContext.Session.GetString("CheckedList");
            if (Data != null)
                List = JsonConvert.DeserializeObject<List<string[]>>(Data);
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form method="post">
        <div class="form-group">
            <label asp-for="LeapYear.Year"></label>
            <input asp-for="LeapYear.Year" class="form-control"><br />
        </div>
        <div><span style="font-weight: bold !important" asp-validation-for="LeapYear.Year" class="text-danger"></span></div>
        <div class="form-group">
            <label asp-for="LeapYear.Name"></label>
            <input asp-for="LeapYear.Name" class="form-control"><br />
        </div>
        <div><span style="font-weight: bold" asp-validation-for="LeapYear.Surname" class="text-danger"></span></div>
         <div class="form-group">
            <label asp-for="LeapYear.Surname"></label>
            <input asp-for="LeapYear.Surname" class="form-control"><br />
        </div>
        <div><span style="font-weight: bold" asp-validation-for="LeapYear.Surname" class="text-danger"></span></div>
        <button type="submit" class="btn btn-primary">Zatwierdż</button>
    </form>
    @if(Model.Arr != null) {
        <div class="alert alert-info">
            @Model.Arr[0] @Model.Arr[1] urodził/a się w @Model.Arr[2] roku. To @Model.Arr[3] był rok przestępny.
        </div>
    }
</div>

Pages/RecentlySearched.cshtml
@page
@model LeapYearDatabase.Pages.RecentlySearchedModel
@{
    ViewData["Title"] = "Recently searched";
}
<h1 class="display-4">Ostatnio szukane</h1>
@if(Model.LeapYears != null) {
    <form method="post">
        <ul class="list-group list-group-flush">
            @foreach(var l in Model.LeapYears)
            {
                <li class="list-group-items">
                    <span>
                        @l.Date @l.Name @l.Surname, @l.Year był rokiem @l.IsLeapYear(l.Year) przestępnym.
                    </span>
                    <input class="btn-primary btn-danger" style="float: right" type="submit" asp-page-handler="DeleteRecord" asp-route-RecordId="@l.Id" value="Usuń" />
                </li>
            }
        </ul>
    </form>
}
else {
    <p>Brak wyników.</p>
}

Pages/SavedInSession.cshtml
@page
@model LeapYearDatabase.Pages.SavedInSessionModel
@{
    ViewData["Title"] = "Data in session";
}
<h1 class="display-4">Dane zapisane w sesji</h1>
@if (Model.List != null)
{
    <ul class="list-group list-group-flush">
        @foreach(string[] Arr in Model.List){
            <li class="list-group-item">@Arr[0] @Arr[1], @Arr[2] - rok @Arr[3] przestępny</li>
        }
    </ul>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeapYearWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeapYearWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">LeapYearWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                            asp-page="/SavedInSession">Saved in session</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                            asp-page="/RecentlySearched">Recently searched</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LeapYearWeb - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>